### ISSUE TITLE
Adding the option to switch to burp collaborator

### ISSUE THREAD

**Issue by shivamprakhar** [whwlsfb/Log4j2Scan#12]
Can you please add the feature to switch to bup collaborator in the extension itself?

**Comment by cydef1** [comment]
could you create a version by default with burp collaborator? dnslog.cn doesn't work, thanks for your BURP plugin
![image](https://user-images.githubusercontent.com/51300087/145776892-2b960224-8d05-44e1-91f1-605e97792455.png)

**Comment by whwlsfb** [comment]
> could you create a version by default with burp collaborator? dnslog.cn doesn't work, thanks for your BURP plugin ![image](https://user-images.githubusercontent.com/51300087/145776892-2b960224-8d05-44e1-91f1-605e97792455.png)

 I uploaded a specially compiled version, please go to the release page and download for burpcollaborator version package

**Comment by shivamprakhar** [comment]
Thanks a lot.

**Comment by cydef1** [comment]
thanks for this version too

**Comment by whwlsfb** [comment]
version `v0.8` add dnslog platform change panel.
