### ISSUE TITLE
how to add plugin

### ISSUE THREAD

**Issue by vansh1** [whwlsfb/Log4j2Scan#14]
how can i add this to burp plugins

**Comment by p01terge1st** [comment]
hi there!
when i try install plugin, have an error:
`java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at burp.arj.a(Unknown Source)
	at burp.arj.<init>(Unknown Source)
	at burp.c2x.a(Unknown Source)
	at burp.cyy.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)`

**Comment by whwlsfb** [comment]
> hi there! when i try install plugin, have an error: `java.lang.ClassNotFoundException: burp.BurpExtender at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at burp.arj.a(Unknown Source) at burp.arj.<init>(Unknown Source) at burp.c2x.a(Unknown Source) at burp.cyy.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832)`

Please try downloading again. The error may be caused by file corruption

**Comment by Captain404** [comment]
Same problem no matter how many times I try donwload it.

**Comment by Captain404** [comment]
> > hi there! when i try install plugin, have an error: `java.lang.ClassNotFoundException: burp.BurpExtender at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at burp.arj.a(Unknown Source) at burp.arj.<init>(Unknown Source) at burp.c2x.a(Unknown Source) at burp.cyy.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832)`
> 
> Please try downloading again. The error may be caused by file corruption

Same problem no matter how many times I try donwload it.

**Comment by whwlsfb** [comment]
> > > hi there! when i try install plugin, have an error: `java.lang.ClassNotFoundException: burp.BurpExtender at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at burp.arj.a(Unknown Source) at burp.arj.<init>(Unknown Source) at burp.c2x.a(Unknown Source) at burp.cyy.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832)`
> > 
> > 
> > Please try downloading again. The error may be caused by file corruption
> 
> Same problem no matter how many times I try download it.

Burpsuite 2021.4 or later is recommended for this plug-in.

**Comment by Captain404** [comment]
> > > > hi there! when i try install plugin, have an error: `java.lang.ClassNotFoundException: burp.BurpExtender at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at burp.arj.a(Unknown Source) at burp.arj.<init>(Unknown Source) at burp.c2x.a(Unknown Source) at burp.cyy.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832)`
> > > 
> > > 
> > > Please try downloading again. The error may be caused by file corruption
> > 
> > 
> > Same problem no matter how many times I try download it.
> 
> Burpsuite 2021.4 or later is recommended for this plug-in.

Thanks for the super fast reply...I'm using Burp Pro v2021.10.3

**Comment by whwlsfb** [comment]
> > > > > hi there! when i try install plugin, have an error: `java.lang.ClassNotFoundException: burp.BurpExtender at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at burp.arj.a(Unknown Source) at burp.arj.<init>(Unknown Source) at burp.c2x.a(Unknown Source) at burp.cyy.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832)`
> > > > 
> > > > 
> > > > Please try downloading again. The error may be caused by file corruption
> > > 
> > > 
> > > Same problem no matter how many times I try download it.
> > 
> > 
> > Burpsuite 2021.4 or later is recommended for this plug-in.
> 
> Thanks for the super fast reply...I'm using Burp Pro v2021.10.3

So... I'm confused,  I am also using burpsuite 2021.10, and I have just downloaded the jar package from GitHub and successfully installed it.

**Comment by Captain404** [comment]
> > > > > > hi there! when i try install plugin, have an error: `java.lang.ClassNotFoundException: burp.BurpExtender at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at burp.arj.a(Unknown Source) at burp.arj.<init>(Unknown Source) at burp.c2x.a(Unknown Source) at burp.cyy.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832)`
> > > > > 
> > > > > 
> > > > > Please try downloading again. The error may be caused by file corruption
> > > > 
> > > > 
> > > > Same problem no matter how many times I try download it.
> > > 
> > > 
> > > Burpsuite 2021.4 or later is recommended for this plug-in.
> > 
> > 
> > Thanks for the super fast reply...I'm using Burp Pro v2021.10.3
> 
> So... I'm confused, I am also using burpsuite 2021.10, and I have just downloaded the jar package from GitHub and successfully installed it.

Working :-) 

![image](https://user-images.githubusercontent.com/58698256/145793940-72c50a00-ed3b-4956-9c9b-a1fc8e2688f8.png)

not sure what was going on with my Burp

**Comment by p01terge1st** [comment]
> > So... I'm confused, I am also using burpsuite 2021.10, and I have just downloaded the jar package from GitHub and successfully installed it.
> 
> Working :-)
> 
> ![image](https://user-images.githubusercontent.com/58698256/145793940-72c50a00-ed3b-4956-9c9b-a1fc8e2688f8.png)
> 
> not sure what was going on with my Burp


Where did you find the JAR file? I only have *.java...
