### ISSUE TITLE
我的只在插件日志能看到回显

### ISSUE THREAD

**Issue by 0x25w** [whwlsfb/Log4j2Scan#17]

**Comment by 0x25w** [comment]
![image](https://user-images.githubusercontent.com/72005182/145747365-cabb280f-5a87-46c0-b5a4-587fcda31af3.png)
![image](https://user-images.githubusercontent.com/72005182/145747383-04d30b8f-b88b-47ce-83df-3a8eb53a98b3.png)

**Comment by whwlsfb** [comment]
> ![image](https://user-images.githubusercontent.com/72005182/145747365-cabb280f-5a87-46c0-b5a4-587fcda31af3.png) ![image](https://user-images.githubusercontent.com/72005182/145747383-04d30b8f-b88b-47ce-83df-3a8eb53a98b3.png)

这是失败的回显
