### ISSUE TITLE
bp版本21.10.3插件无法生效

### ISSUE THREAD

**Issue by TheCryingGame** [whwlsfb/Log4j2Scan#2]
load成功
![image](https://user-images.githubusercontent.com/48227194/145550294-8c7943f9-9855-4c37-b439-10e775f68ba0.png)
访问tools本地环境
![image](https://user-images.githubusercontent.com/48227194/145550392-5d3d0c8e-572f-46d1-a617-4e6a9576f502.png)
![image](https://user-images.githubusercontent.com/48227194/145550444-c74fe265-f488-4cdd-ab66-a201a5b5991e.png)

**Comment by whwlsfb** [comment]
默认使用的Dnslog.cn平台挂了，可以修改使用内置的ceye的dnslog

**Comment by whwlsfb** [comment]
#1

**Comment by IamNoNmae** [comment]
我现在也是这个问题，扫描出来，发现靶机环境没有对应的漏洞报错，还是走的默认漏洞检查
<img width="405" alt="1639154270(1)" src="https://user-images.githubusercontent.com/83331553/145609066-9d3a33bf-7c6d-4fdc-a9d8-a79f73d14ebd.png">

**Comment by whwlsfb** [comment]
> 我现在也是这个问题，扫描出来，发现靶机环境没有对应的漏洞报错，还是走的默认漏洞检查 <img alt="1639154270(1)" width="405" src="https://user-images.githubusercontent.com/83331553/145609066-9d3a33bf-7c6d-4fdc-a9d8-a79f73d14ebd.png">

请看一下插件日志里是否有错误信息，另外确认下漏洞位置是否是插件的支持范围之内。
