### ISSUE TITLE
How to add this extention in Burp Suite?

### ISSUE THREAD

**Issue by nefski3** [whwlsfb/Log4j2Scan#24]
If I try Extender and choose to load BurpExtender.java I always getting "java.lang.ClassNotFoundException: burp.BurpExtender" error

**Comment by abewartech** [comment]
Now is success

I download the JAR file on https://github.com/whwlsfb/Log4j2Scan/releases

**Comment by nefski3** [comment]
> [abewartech](/abewartech)

Ah, Thank you!
