### ISSUE TITLE
dnslog.cn/getdomain.php 返回404了

### ISSUE THREAD

**Issue by nmweizi** [whwlsfb/Log4j2Scan#25]
看正确的好像变成这样了
GET /getsubdomain.php?t=0.892059940138602 HTTP/1.1
Host: www.dnslog.cn
Pragma: no-cache
Cache-Control: no-cache

**Comment by nmweizi** [comment]
一会又改成/getdomain.php?t=0.4161605429783808

**Comment by whwlsfb** [comment]
`v0.8.1`已修正
