### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by book4yi** [whwlsfb/Log4j2Scan#28]
建议一次性在数据包中添加所有的请求头字段，比如X-Originating-IP、Client-IP、X-Forwarded-For全部放到一个请求包中，不然对一个数据包，插件要发送上百个请求太慢了（或者在GUI界面允许用户选择是否这么做）

**Comment by whwlsfb** [comment]
> 建议一次性在数据包中添加所有的请求头字段，比如X-Originating-IP、Client-IP、X-Forwarded-For全部放到一个请求包中，不然对一个数据包，插件要发送上百个请求太慢了（或者在GUI界面允许用户选择是否这么做）

该提议已在开发计划中，下一版用了个折中的方案，已存在的header还是挨个fuzz一遍，不存在的，最后一发全怼上。

平均每个url能减少10~20个请求包。

**Comment by whwlsfb** [comment]
`v0.9`已更新该功能。
