### ISSUE TITLE
内网检测版本

### ISSUE THREAD

**Issue by raymonYuan** [whwlsfb/Log4j2Scan#37]
之前基于大佬的0.7版本写了个内网扫描的，但是paramfuzz里面有些问题。 问下这个0.9版本的RevSuitRMI是给内网用的么？  
微信群进不去 求拉vx:Coder19

**Comment by whwlsfb** [comment]
> 之前基于大佬的0.7版本写了个内网扫描的，但是paramfuzz里面有些问题。 问下这个0.9版本的RevSuitRMI是给内网用的么？ 微信群进不去 求拉vx:Coder19

是的内网可以用RMI
