### ISSUE TITLE
这个错误是什么

### ISSUE THREAD

**Issue by Ks236** [whwlsfb/Log4j2Scan#40]
burp.utils.ParamReplace@5cea84c9
burp.utils.ParamReplace@ed658a0
burp.utils.ParamReplace@23b61398
burp.utils.ParamReplace@52a161d
burp.utils.ParamReplace@dee16bd
burp.utils.ParamReplace@31c15cf8
burp.utils.ParamReplace@22f8a38b
burp.utils.ParamReplace@7737c33
很多 有时又没有

**Comment by whwlsfb** [comment]
这个没事的，只是日志打印，不是报错
