### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by book4yi** [whwlsfb/Log4j2Scan#41]
发现对一些静态资源也会注入payload，像一些图片、CSS、js脚本、视频等响应类型可以过滤掉

**Comment by whwlsfb** [comment]
请问你使用的是哪个版本？0.6版本中已经对常见的静态扩展名进行了过滤了，如有遗漏麻烦提供下。

**Comment by book4yi** [comment]
.js.map文件未过滤

**Comment by whwlsfb** [comment]
收到，下个版本加入该扩展名的过滤
