### ISSUE TITLE
已不兼容burpsuite 2022.9.1

### ISSUE THREAD

**Issue by k-fire** [whwlsfb/Log4j2Scan#49]
日志如下：
```
Log4j2Scan v0.12
Log4j2Scan loaded successfully!

Scanning: http://123.58.224.8:30596/hello?payload=111
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
Scan complete: http://123.58.224.8:30596/hello?payload=111 - No issue found.
Scanning: http://123.58.224.8:30596/
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
java.lang.IllegalArgumentException: method GET must not have a request body.
Scan complete: http://123.58.224.8:30596/ - No issue found.
Log4j2Scan loaded successfully!

Log4j2Scan loaded successfully!

Scanning: http://123.58.224.8:30596/hello?payload=111
Scan complete: http://123.58.224.8:30596/hello?payload=111 - No issue found.
```
已经无法正常发包，logger无发包记录。

**Comment by solarpeng502** [comment]
我的也是，jdk14，编译后也是导入也是这样

**Comment by whwlsfb** [comment]
问题已确认并修复，下个版本将会修复该问题，或者可直接拉取master分支源码编译解决

**Comment by whwlsfb** [comment]
> > 问题已确认并修复，下个版本将会修复该问题，或者可直接拉取master分支源码编译解决
> 
> 最新编译，jdk18： ![image](https://user-images.githubusercontent.com/40354487/197122602-f053a209-8485-48d5-9ddc-ff5c06dd3589.png)
> 
> ```
> 	at burp.scanner.Log4j2Scanner.doScan(Log4j2Scanner.java:205)
> 	at burp.scanner.Log4j2Scanner.doPassiveScan(Log4j2Scanner.java:186)
> 	at burp.lno.passiveAudit(Unknown Source)
> 	at burp.s_.run(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> java.io.InterruptedIOException: timeout
> 	at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
> 	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
> 	at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
> 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
> 	at burp.utils.HttpUtils.RawRequest(HttpUtils.java:50)
> 	at burp.scanner.Log4j2Scanner.sendRequest(Log4j2Scanner.java:532)
> 	at burp.scanner.Log4j2Scanner.headerFuzz(Log4j2Scanner.java:364)
> 	at burp.scanner.Log4j2Scanner.doScan(Log4j2Scanner.java:205)
> 	at burp.scanner.Log4j2Scanner.doPassiveScan(Log4j2Scanner.java:186)
> 	at burp.lno.passiveAudit(Unknown Source)
> 	at burp.s_.run(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.net.SocketException: Socket closed
> 	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248)
> 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327)
> 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
> 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
> 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
> 	at okio.InputStreamSource.read(JvmOkio.kt:90)
> 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
> 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
> 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
> 	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
> 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
> 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
> 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
> 	... 13 more
> java.net.SocketException: Connection reset
> 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
> 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
> 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
> 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
> 	at okio.InputStreamSource.read(JvmOkio.kt:90)
> 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
> 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
> 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
> 	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
> 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
> 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
> 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
> 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
> 	at burp.utils.HttpUtils.RawRequest(HttpUtils.java:50)
> 	at burp.scanner.Log4j2Scanner.sendRequest(Log4j2Scanner.java:532)
> 	at burp.scanner.Log4j2Scanner.headerFuzz(Log4j2Scanner.java:378)
> 	at burp.scanner.Log4j2Scanner.doScan(Log4j2Scanner.java:205)
> 	at burp.scanner.Log4j2Scanner.doPassiveScan(Log4j2Scanner.java:186)
> 	at burp.lno.passiveAudit(Unknown Source)
> 	at burp.s_.run(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> java.io.InterruptedIOException: timeout
> 	at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
> 	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
> 	at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
> 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
> 	at burp.utils.HttpUtils.RawRequest(HttpUtils.java:50)
> 	at burp.scanner.Log4j2Scanner.sendRequest(Log4j2Scanner.java:532)
> 	at burp.scanner.Log4j2Scanner.headerFuzz(Log4j2Scanner.java:364)
> 	at burp.scanner.Log4j2Scanner.doScan(Log4j2Scanner.java:205)
> 	at burp.scanner.Log4j2Scanner.doPassiveScan(Log4j2Scanner.java:186)
> 	at burp.lno.passiveAudit(Unknown Source)
> 	at burp.s_.run(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.net.SocketException: Socket closed
> 	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248)
> 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327)
> 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
> 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
> 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
> 	at okio.InputStreamSource.read(JvmOkio.kt:90)
> 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
> 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
> 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
> 	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
> 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
> 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
> 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
> 	... 13 more
> ```

这些是表示工作正常的，后续会隐藏掉

**Comment by whwlsfb** [comment]
可以测试下靶场，看下是否正常工作 @k-fire
