### ISSUE TITLE
Dnslog init failed!

### ISSUE THREAD

**Issue by oppsec** [whwlsfb/Log4j2Scan#5]
Hello!
 
I've added the .jar file to my Burp Extensions extender tab and I get this following error:

initDomain failed: www.dnslog.cn: No address associated with hostname

**Comment by whwlsfb** [comment]
This plugin needs to use the echo of dnslog.cn as the basis for judgment, please confirm whether you can access http://www.dnslog.cn normally.

**Comment by VikasUpadhyay0** [comment]
can not access this can you share any alternative.
