### ISSUE TITLE
为什么我设置了revsuit rmi 但是探测仍然是使用的dnslog呢？

### ISSUE THREAD

**Issue by githublihaha** [whwlsfb/Log4j2Scan#50]
设置的revsuit rmi，并且应用了
![image](https://user-images.githubusercontent.com/43808858/194831572-3fa0e886-59af-4475-8553-55e2926fe1b8.png)
从extender的输出来看仍然是使用 dnslog测试的
![image](https://user-images.githubusercontent.com/43808858/194831738-9ce1398c-fe5a-42ac-99ee-7f2ac5cbfe26.png)
revsuit平台的 rmi log 也是没有记录的
![image](https://user-images.githubusercontent.com/43808858/194831779-4c9c3e0a-9d51-4c02-95bd-2db53bcfc7f4.png)

**Comment by githublihaha** [comment]
burpsuite 版本 2021.8
java11

**Comment by githublihaha** [comment]
插件下载的是最新版本的

**Comment by whwlsfb** [comment]
修改之后点击`Save&Apply`，随后产生的新扫描任务才会使用rmi。
也就是说，如果目标URL的扫描任务在Apply新配置前已经启动了的话，是无法使用新的扫描配置的。
