### ISSUE TITLE
目前dig平台已经恢复，但是插件获取dig依然会报错，这个问题在一周多之前已经发现，当时dig是正常的

### ISSUE THREAD

**Issue by coinbase6516** [whwlsfb/Log4j2Scan#63]
目前dig已经恢复正常 但是插件获取dig域名还是报错 会出现报错日志 希望作者尽快修复  我已经用了很久本插件 [上述问题都是使用中突然出现的异常发现的
![1690888208380](https://github.com/whwlsfb/Log4j2Scan/assets/128479758/158130b3-ecf8-4d44-8796-4ce82726158f)

**Comment by whwlsfb** [comment]
该问题后续将在 #62 中跟踪。
